name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: |
        cd Discreet-GUI/
        dotnet restore
      
    - name: Publish [WIN-x64]
      run: |
        cd Discreet-GUI/
        dotnet publish --configuration Release --runtime win-x64 --framework net6.0 --self-contained true -p:ReadyToRun=true
        
    - name: Zip [WIN-X64]
      uses: montudor/action-zip@v1
      with:
        args: zip -qq -r win-x64.zip Discreet-GUI/WPF/bin/Release/net6.0/win-x64/publish

    - name: Create the Github Release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: ${{ steps.version.outputs.version }}
        tag_name: ${{ github.ref }}
        body: CHANGELOG
      env:
        GITHUB_TOKEN: ${{ github.token }}
        
    - name: Upload [WIN-x64] archive to the release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: win-x64.zip
        asset_name: win-x64.zip
        asset_content_type: application/zip
